### ISSUE TITLE
Rebind the top row of keys to do as the icons suggest

### ISSUE THREAD

**Issue by ColtonDRG** [GalliumOS/galliumos-laptop#2]
This issue belongs here.
Previous discussion on the issue takes place in these threads
https://github.com/GalliumOS/galliumos-device-c710/issues/4
https://github.com/GalliumOS/galliumos-base/issues/2
We should use this thread for all future discussion because this is where it belongs.

**Comment by Roechamboe** [comment]
I can build xbind configs for the devices but lets get this locked down. Holding down function key should show binds specific for that model.
 
How does this sound:
>Pictures do what they say(wifi brings up network manager)
>Fn+Picture key in respected order is F1-F10(C720)/F1-F11(C710)
>Shift+Fn+F1(F11 on 720)(F12 on C710)
>Shift+Fn+F2(F12 on C720)
>Fn+Up(pgup)
>Fn+Down(pgdn)
>Fn+Left(home)
>Fn+Right(end)
>Fn+backspace(del)

**Comment by ColtonDRG** [comment]
Sounds good, but there's one problem. The C710 is the only model with an fn key, and it has most of those other keys. The C710 has it's own F12, pgup, pgdn, home, end, ins, and del keys. We will probably need a separate config for the C710, which I will write after we have the "universal" one.

For the universal model,
Search+Icon key in respected order is F1-F10
Shift + Search + F1 (F11)
Shift + Search + F2 (F12)
Search + Up (pgup)
Search + Down (pgdn)
Search + Left (home)
Search + Right (end)
Search + Backspace (del)
Search + Return (ins)

For the C710 ONLY,
Fn+Icon key in respected order is F1-F12
None of the others are nessesary
Perhaps have a customizable keybind for F12 without holding fn?

Unfortunately, the Chromebook's rather silly keyboard layout makes this a much broader issue than I initially thought. Luckily, they aren't changing it any more, so moving forward, the universal model should work on everything, and we'll only need the special configs for the C710, Cr48, and other very early Chromebooks.

**Comment by hugegreenbug** [comment]
xbindkeys -k 

will give you want you need to put in your ~/.xbindkeysrc. When you are happy with it, please commit it to the galliumos-device-c710 package in /etc/skel.
